title: "My blog"
description: "Notes, ideas, and projects"
# Theme maintained by GitHub Pages
theme: minima

# Useful plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Adjust this when you add a custom domain
url: "https://0x574R.github.io"
